package com.mcf.davidee.autojoin;

import java.util.Arrays;

import net.minecraft.client.multiplayer.ServerAddress;
import net.minecraftforge.common.Configuration;

import com.mcf.davidee.autojoin.forge.ConnectionHandler;
import com.mcf.davidee.autojoin.forge.GuiListener;
import com.mcf.davidee.autojoin.gui.AutoJoinScreen;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.TickRegistry;
import cpw.mods.fml.relauncher.Side;

@Mod(modid="AutoJoin", name="Auto Join", version=AutoJoin.VERSION, dependencies="after:guilib")
@NetworkMod(connectionHandler = ConnectionHandler.class)
public class AutoJoin {
	
	public static final int PROTOCOL_VER = 74;
	public static final String VERSION = "1.6.2.0";
	
	@Instance("AutoJoin")
	public static AutoJoin instance;
	
	private AJConfig config;
	public ServerInfo lastServer;
	public AutoJoinScreen screen;
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		config = new AJConfig(new Configuration(event.getSuggestedConfigurationFile()));
		
		ModMetadata modMeta = event.getModMetadata();
		modMeta.authorList = Arrays.asList(new String[] { "Davidee" });
		modMeta.autogenerated = false;
		modMeta.credits = "Thanks to Mojang, Forge, and all your support.";
		modMeta.description = "Easily join a populated public server.";
		modMeta.url = "http://www.minecraftforum.net/topic/1922957-/";
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event) {
		TickRegistry.registerScheduledTickHandler(new GuiListener(), Side.CLIENT);
	}
	
	public AJConfig getConfig() {
		return config;
	}
	
	public void resetCache() {
		lastServer = null;
		screen = null;
	}
}
